title: Y.WANG
logo: /assets/img/logo3.png
description: Memoirs about me, the music and the night. Memoirs about think-ism and practice-ism.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

github_username:  treywangcqu
twitter_username: treywangcqu

header_pages:
  - about.md
  - blog.md

markdown:         kramdown
highlighter:      rouge


