title: Y.WANG
description: Memoirs about me, the music and the night. Memoirs about think-ism and practice-ism.
show_downloads: false
google_analytics:

author: Y.WANG
email: y.wang@reaticle.com
iconfont_url: https://at.alicdn.com/t/font_2714580_eqcgguazg7q.css
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

markdown:         kramdown
highlighter:      rouge



paginate: 7
paginate_path: "/blog/page:num/"
